const GET_AGENCIES = 'GET_AGENCIES'
const GET_CATEGORIES = 'GET_CATEGORIES'
const GET_PRICES = 'GET_PRICES'
const GET_AGENCIES_ERROR = 'GET_AGENCIES_ERROR'
const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR'
const GET_PRICES_ERROR = 'GET_PRICES_ERROR'
const SET_PRICES_FILTERS = 'SET_PRICES_FILTERS'
const SORT_PRICES = 'SORT_PRICES'

export default {
  GET_AGENCIES,
  GET_CATEGORIES,
  GET_PRICES,
  GET_AGENCIES_ERROR,
  GET_CATEGORIES_ERROR,
  GET_PRICES_ERROR,
  SET_PRICES_FILTERS,
  SORT_PRICES
}
